### ISSUE TITLE
oblig1parser not visible in Compiler.java

### ISSUE THREAD

**Issue by oddgfa** [PavelJurasek/INF5110#1]
I believe the generated lexer and parser should be put in `src/oblig1parser` so it is visible for `src/compiler/Compiler.java`. Should the build file be changed to support this? I had a look at the xml file, but it was scary.

**Comment by PavelJurasek** [comment]
Everything works just fine for me. Did you run ```compile``` task in Ant?

**Comment by oddgfa** [comment]
You're right. It was just my linter acting up.
