### ISSUE TITLE
Writing operators in unambiguous grammar

### ISSUE THREAD

**Issue by saliha-sajid** [PavelJurasek/INF5110#5]
In ambiguous grammar we used all operators directly by using quotes like "<". 

Writing a production for terminals in unambiguous grammar leads to errors. 
 incompatible types: String cannot be converted to AritOpExpr
    [javac]              RESULT = "*";

How can we fix this? One way that I could think of is to make classes for operators. But then we get a whole new set of syntax tree.

**Comment by PavelJurasek** [comment]
Did you manage to fix it?

**Comment by saliha-sajid** [comment]
Yes. Wrote real names of terminals instead.
